package com.smascaro.trackmixing.common

//TODO: move to resource file
const val NODE_SERVER_NAME = "DESKTOP-L9MQBB7"

//TODO: move to resource file
const val NODE_SERVER_PORT = 8081
const val NODE_BASE_URL = "http://$NODE_SERVER_NAME:$NODE_SERVER_PORT/"
const val NODE_API_FETCH_AVAILABLE = "availableTracks"
const val NOTIFICATION_ID = 2000
const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
const val NOTIFICATION_MEDIA_SESSION_TAG = "NOTIFICATION_MEDIA_SESSION_TAG"
const val NOTIFICATION_ACTION_PLAY_MASTER = "NOTIFICATION_ACTION_PLAY_MASTER"
const val NOTIFICATION_ACTION_PAUSE_MASTER = "NOTIFICATION_ACTION_PAUSE_MASTER"
const val NOTIFICATION_ACTION_MUTE_VOCALS = "NOTIFICATION_ACTION_MUTE_VOCALS"
const val NOTIFICATION_ACTION_UNMUTE_VOCALS = "NOTIFICATION_ACTION_UNMUTE_VOCALS"
const val NOTIFICATION_ACTION_MUTE_OTHER = "NOTIFICATION_ACTION_MUTE_OTHER"
const val NOTIFICATION_ACTION_UNMUTE_OTHER = "NOTIFICATION_ACTION_UNMUTE_OTHER"
const val NOTIFICATION_ACTION_MUTE_BASS = "NOTIFICATION_ACTION_MUTE_BASS"
const val NOTIFICATION_ACTION_UNMUTE_BASS = "NOTIFICATION_ACTION_UNMUTE_BASS"
const val NOTIFICATION_ACTION_MUTE_DRUMS = "NOTIFICATION_ACTION_MUTE_DRUMS"
const val NOTIFICATION_ACTION_UNMUTE_DRUMS = "NOTIFICATION_ACTION_UNMUTE_DRUMS"
const val NOTIFICATION_ACTION_START_SERVICE = "NOTIFICATION_ACTION_START_SERVICE"
const val NOTIFICATION_ACTION_STOP_SERVICE = "NOTIFICATION_ACTION_STOP_SERVICE"
const val NOTIFICATION_ACTION_LOAD_TRACK = "NOTIFICATION_ACTION_LOAD_TRACK"
const val NOTIFICATION_EXTRA_LOAD_TRACK_PARAM_KEY = "NOTIFICATION_EXTRA_LOAD_TRACK_PARAM_KEY"

//Shared preferences
const val SHARED_PREFERENCES_PLAYBACK = "SHARED_PREFERENCES_PLAYBACK"
const val SHARED_PREFERENCES_PLAYBACK_IS_PLAYING = "SHARED_PREFERENCES_PLAYBACK_IS_PLAYING"
const val SHARED_PREFERENCES_PLAYBACK_SONG_PLAYING = "SHARED_PREFERENCES_PLAYBACK_SONG_PLAYING"