package com.smascaro.trackmixing.common

//TODO: move to resource file
const val NODE_SERVER_NAME = "DESKTOP-L9MQBB7"

//TODO: move to resource file
const val NODE_SERVER_PORT = 8081
const val NODE_BASE_URL = "http://$NODE_SERVER_NAME:$NODE_SERVER_PORT/"
const val NODE_API_FETCH_AVAILABLE = "availableTracks"
const val EXTRA_BASE_TRACKS_PATH = "EXTRA_BASE_TRACKS_PATH"
const val SAVED_STATE_SORT_CRITERIA = "SAVED_STATE_SORT_CRITERIA"
const val SAVED_STATE_SELECTED_ITEM_POSITION = "SAVED_STATE_SELECTED_ITEM_POSITION"
const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
const val NOTIFICATION_MEDIA_SESSION_TAG = "NOTIFICATION_MEDIA_SESSION_TAG"
const val NOTIFICATION_ACTION_START_SERVICE = "NOTIFICATION_ACTION_START_SERVICE"
const val NOTIFICATION_ACTION_PLAY_MASTER = "NOTIFICATION_ACTION_PLAY_MASTER"
const val NOTIFICATION_ACTION_PAUSE_MASTER = "NOTIFICATION_ACTION_PAUSE_MASTER"
const val NOTIFICATION_ACTION_MUTE_VOCALS = "NOTIFICATION_ACTION_MUTE_VOCALS"
const val NOTIFICATION_ACTION_UNMUTE_VOCALS = "NOTIFICATION_ACTION_UNMUTE_VOCALS"
const val NOTIFICATION_ACTION_MUTE_OTHER = "NOTIFICATION_ACTION_MUTE_OTHER"
const val NOTIFICATION_ACTION_UNMUTE_OTHER = "NOTIFICATION_ACTION_UNMUTE_OTHER"
const val NOTIFICATION_ACTION_MUTE_BASS = "NOTIFICATION_ACTION_MUTE_BASS"
const val NOTIFICATION_ACTION_UNMUTE_BASS = "NOTIFICATION_ACTION_UNMUTE_BASS"
const val NOTIFICATION_ACTION_MUTE_DRUMS = "NOTIFICATION_ACTION_MUTE_DRUMS"
const val NOTIFICATION_ACTION_UNMUTE_DRUMS = "NOTIFICATION_ACTION_UNMUTE_DRUMS"
const val NOTIFICATION_REQUEST_CODE_PLAY_MASTER = 1000
const val NOTIFICATION_REQUEST_CODE_PAUSE_MASTER = 1001
const val NOTIFICATION_ID = 2000
const val FOREGROUND_SERVICE_ID = 2001