package com.smascaro.trackmixing.common.utils

const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
const val PLAYER_NOTIFICATION_ID = 2000
const val PLAYER_NOTIFICATION_MEDIA_SESSION_TAG = "PLAYER_NOTIFICATION_MEDIA_SESSION_TAG"
const val PLAYER_NOTIFICATION_ACTION_PLAY_MASTER = "PLAYER_NOTIFICATION_ACTION_PLAY_MASTER"
const val PLAYER_NOTIFICATION_ACTION_PAUSE_MASTER = "PLAYER_NOTIFICATION_ACTION_PAUSE_MASTER"
const val PLAYER_NOTIFICATION_ACTION_LAUNCH_PLAYER = "PLAYER_NOTIFICATION_ACTION_LAUNCH_PLAYER"
const val PLAYER_NOTIFICATION_ACTION_START_SERVICE = "PLAYER_NOTIFICATION_ACTION_START_SERVICE"
const val PLAYER_NOTIFICATION_ACTION_STOP_SERVICE = "PLAYER_NOTIFICATION_ACTION_STOP_SERVICE"
const val PLAYER_NOTIFICATION_ACTION_LOAD_TRACK = "PLAYER_NOTIFICATION_ACTION_LOAD_TRACK"
const val PLAYER_NOTIFICATION_EXTRA_LOAD_TRACK_PARAM_KEY =
    "PLAYER_NOTIFICATION_EXTRA_LOAD_TRACK_PARAM_KEY"
const val PLAYER_NOTIFICATION_EXTRA_START_PLAYING_PARAM_KEY =
    "PLAYER_NOTIFICATION_EXTRA_START_PLAYING_PARAM_KEY"
const val DOWNLOAD_NOTIFICATION_ID = 2001
const val DOWNLOAD_NOTIFICATION_ACTION_START_DOWNLOAD = "DOWNLOAD_NOTIFICATION_ACTION_START_SERVICE"
const val DOWNLOAD_NOTIFICATION_EXTRA_START_SERVICE_PARAM_KEY =
    "DOWNLOAD_NOTIFICATION_EXTRA_START_SERVICE_PARAM_KEY"

//Shared preferences
const val SHARED_PREFERENCES_PLAYBACK = "SHARED_PREFERENCES_PLAYBACK"
const val SHARED_PREFERENCES_PLAYBACK_IS_PLAYING = "SHARED_PREFERENCES_PLAYBACK_IS_PLAYING"
const val SHARED_PREFERENCES_PLAYBACK_SONG_PLAYING = "SHARED_PREFERENCES_PLAYBACK_SONG_PLAYING"
const val SHARED_PREFERENCES_PLAYBACK_CURRENT_TIMESTAMP_MILLIS =
    "SHARED_PREFERENCES_PLAYBACK_CURRENT_TIMESTAMP_MILLIS"
const val SHARED_PREFERENCES_PLAYBACK_CURRENT_VOLUMES =
    "SHARED_PREFERENCES_PLAYBACK_CURRENT_VOLUMES"
const val MEDIA_PLAYER_MAX_VOLUME = 100f
const val YOUTUBE_API_BASE_URL = "https://www.googleapis.com/youtube/v3/"
const val AWS_S3_DOWNLOAD_DATA_BASE_URL = "https://sm01-s3-tracks.s3-eu-west-1.amazonaws.com/"
const val AWS_S3_DOWNLOAD_DATA_INFO_FILE_BASE_URL = AWS_S3_DOWNLOAD_DATA_BASE_URL
const val AWS_S3_DOWNLOAD_DATA_BUNDLES_BASE_URL = "${AWS_S3_DOWNLOAD_DATA_BASE_URL}bundles/"
const val AWS_S3_TEST_DATA_INFO_FILE_RESOURCE = "test_data_bundle.json"