package com.smascaro.trackmixing.common.models

const val TRACK_TITLE = "TEST_TITLE"
const val TRACK_AUTHOR = "TEST_AUTHOR"
const val TRACK_VIDEO_KEY = "TEST_VIDEO_KEY"
const val TRACK_THUMBNAIL_URL = "TEST_THUMBNAIL_URL"
const val TRACK_SECONDS_LONG = 120
const val TRACK_REQUESTED_TIMESTAMP = "TEST_REQUESTED_TIMESTAMP"
const val TRACK_DOWNLOAD_PATH = "TEST_DOWNLOAD_PATH"

const val DOWNLOAD_ENTITY_ID = 1
const val DOWNLOAD_ENTITY_TITLE = "DOWNLOAD_ENTITY_TITLE"
const val DOWNLOAD_ENTITY_AUTHOR = "DOWNLOAD_ENTITY_AUTHOR"
const val DOWNLOAD_ENTITY_VIDEO_KEY = "DOWNLOAD_ENTITY_VIDEO_KEY"
const val DOWNLOAD_ENTITY_THUMBNAIL_URL = "DOWNLOAD_ENTITY_THUMBNAIL_URL"
const val DOWNLOAD_ENTITY_SECONDS_LONG = 120
const val DOWNLOAD_ENTITY_REQUESTED_TIMESTAMP = "DOWNLOAD_ENTITY_REQUESTED_TIMESTAMP"
const val DOWNLOAD_ENTITY_DOWNLOAD_PATH = "DOWNLOAD_ENTITY_DOWNLOAD_PATH"
const val DOWNLOAD_ENTITY_QUALITY = "DOWNLOAD_ENTITY_QUALITY"
const val DOWNLOAD_ENTITY_STATUS = 0