package com.smascaro.trackmixing.common.models

const val TRACK_TITLE = "TEST_TITLE"
const val TRACK_AUTHOR = "TEST_AUTHOR"
const val TRACK_VIDEO_KEY = "TEST_VIDEO_KEY"
const val TRACK_THUMBNAIL_URL = "TEST_THUMBNAIL_URL"
const val TRACK_SECONDS_LONG = 120
const val TRACK_REQUESTED_TIMESTAMP = "TEST_REQUESTED_TIMESTAMP"
const val TRACK_DOWNLOAD_PATH = "TEST_DOWNLOAD_PATH"

const val DOWNLOAD_ENTITY_1_ID = 1
const val DOWNLOAD_ENTITY_1_TITLE = "DOWNLOAD_ENTITY_1_TITLE"
const val DOWNLOAD_ENTITY_1_AUTHOR = "DOWNLOAD_ENTITY_1_AUTHOR"
const val DOWNLOAD_ENTITY_1_VIDEO_KEY = "DOWNLOAD_ENTITY_1_VIDEO_KEY"
const val DOWNLOAD_ENTITY_1_THUMBNAIL_URL = "DOWNLOAD_ENTITY_1_THUMBNAIL_URL"
const val DOWNLOAD_ENTITY_1_SECONDS_LONG = 120
const val DOWNLOAD_ENTITY_1_REQUESTED_TIMESTAMP = "DOWNLOAD_ENTITY_1_REQUESTED_TIMESTAMP"
const val DOWNLOAD_ENTITY_1_DOWNLOAD_PATH = "DOWNLOAD_ENTITY_1_DOWNLOAD_PATH"
const val DOWNLOAD_ENTITY_1_QUALITY = "DOWNLOAD_ENTITY_1_QUALITY"
const val DOWNLOAD_ENTITY_1_STATUS = 0

const val DOWNLOAD_ENTITY_2_ID = 2
const val DOWNLOAD_ENTITY_2_TITLE = "DOWNLOAD_ENTITY_2_TITLE"
const val DOWNLOAD_ENTITY_2_AUTHOR = "DOWNLOAD_ENTITY_2_AUTHOR"
const val DOWNLOAD_ENTITY_2_VIDEO_KEY = "DOWNLOAD_ENTITY_2_VIDEO_KEY"
const val DOWNLOAD_ENTITY_2_THUMBNAIL_URL = "DOWNLOAD_ENTITY_2_THUMBNAIL_URL"
const val DOWNLOAD_ENTITY_2_SECONDS_LONG = 160
const val DOWNLOAD_ENTITY_2_REQUESTED_TIMESTAMP = "DOWNLOAD_ENTITY_2_REQUESTED_TIMESTAMP"
const val DOWNLOAD_ENTITY_2_DOWNLOAD_PATH = "DOWNLOAD_ENTITY_2_DOWNLOAD_PATH"
const val DOWNLOAD_ENTITY_2_QUALITY = "DOWNLOAD_ENTITY_2_QUALITY"
const val DOWNLOAD_ENTITY_2_STATUS = 0

const val DOWNLOAD_ENTITY_3_ID = 1
const val DOWNLOAD_ENTITY_3_TITLE = "DOWNLOAD_ENTITY_3_TITLE"
const val DOWNLOAD_ENTITY_3_AUTHOR = "DOWNLOAD_ENTITY_3_AUTHOR"
const val DOWNLOAD_ENTITY_3_VIDEO_KEY = "DOWNLOAD_ENTITY_3_VIDEO_KEY"
const val DOWNLOAD_ENTITY_3_THUMBNAIL_URL = "DOWNLOAD_ENTITY_3_THUMBNAIL_URL"
const val DOWNLOAD_ENTITY_3_SECONDS_LONG = 180
const val DOWNLOAD_ENTITY_3_REQUESTED_TIMESTAMP = "DOWNLOAD_ENTITY_3_REQUESTED_TIMESTAMP"
const val DOWNLOAD_ENTITY_3_DOWNLOAD_PATH = "DOWNLOAD_ENTITY_3_DOWNLOAD_PATH"
const val DOWNLOAD_ENTITY_3_QUALITY = "DOWNLOAD_ENTITY_3_QUALITY"
const val DOWNLOAD_ENTITY_3_STATUS = 1

const val DOWNLOAD_ENTITY_4_ID = 2
const val DOWNLOAD_ENTITY_4_TITLE = "DOWNLOAD_ENTITY_4_TITLE"
const val DOWNLOAD_ENTITY_4_AUTHOR = "DOWNLOAD_ENTITY_4_AUTHOR"
const val DOWNLOAD_ENTITY_4_VIDEO_KEY = "DOWNLOAD_ENTITY_4_VIDEO_KEY"
const val DOWNLOAD_ENTITY_4_THUMBNAIL_URL = "DOWNLOAD_ENTITY_4_THUMBNAIL_URL"
const val DOWNLOAD_ENTITY_4_SECONDS_LONG = 200
const val DOWNLOAD_ENTITY_4_REQUESTED_TIMESTAMP = "DOWNLOAD_ENTITY_4_REQUESTED_TIMESTAMP"
const val DOWNLOAD_ENTITY_4_DOWNLOAD_PATH = "DOWNLOAD_ENTITY_4_DOWNLOAD_PATH"
const val DOWNLOAD_ENTITY_4_QUALITY = "DOWNLOAD_ENTITY_4_QUALITY"
const val DOWNLOAD_ENTITY_4_STATUS = 2